"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const cartController_1 = require("../controllers/cartController");
const router = (0, express_1.Router)();
router.get("/", authMiddleware_1.authMiddleware, cartController_1.showCart);
router.post("/create", authMiddleware_1.authMiddleware, cartController_1.findOrCreateCart);
router.post("/add/:variantId", authMiddleware_1.authMiddleware, cartController_1.addItemToCart);
router.put("/:variantId", authMiddleware_1.authMiddleware, cartController_1.updateCartItem);
router.delete("/:variantId", authMiddleware_1.authMiddleware, cartController_1.removeFromCart);
exports.default = router;
