"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const userController_1 = require("../controllers/userController");
const router = (0, express_1.Router)();
router.get("/", authMiddleware_1.authMiddleware, userController_1.showProfile);
router.put("/", authMiddleware_1.authMiddleware, userController_1.editProfile);
router.delete("/", authMiddleware_1.authMiddleware, userController_1.deleteAccount);
exports.default = router;
